#############################################################################
# Makefile for building: ECGKW
# Generated by qmake (2.01a) (Qt 4.6.0) on: ?? ???. 25 16:13:41 2009
# Project:  ECGKW.pro
# Template: app
# Command: /home/envek/qtsdk/qt/bin/qmake -spec ../qtsdk/qt/mkspecs/linux-g++ -unix -o Makefile ECGKW.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qtsdk/qt/mkspecs/linux-g++ -I. -I../qtsdk/qt/include/QtCore -I../qtsdk/qt/include/QtGui -I../qtsdk/qt/include/QtOpenGL -I../qtsdk/qt/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/envek/qtsdk/qt/lib
LIBS          = $(SUBLIBS)  -L/home/envek/qtsdk/qt/lib -L/usr/X11R6/lib -lQtOpenGL -L/home/envek/qtsdk/qt/lib -L/usr/X11R6/lib -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/envek/qtsdk/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		glwidget.cpp moc_mainwindow.cpp \
		moc_glwidget.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		glwidget.o \
		moc_mainwindow.o \
		moc_glwidget.o \
		qrc_resources.o
DIST          = ../qtsdk/qt/mkspecs/common/g++.conf \
		../qtsdk/qt/mkspecs/common/unix.conf \
		../qtsdk/qt/mkspecs/common/linux.conf \
		../qtsdk/qt/mkspecs/qconfig.pri \
		../qtsdk/qt/mkspecs/features/qt_functions.prf \
		../qtsdk/qt/mkspecs/features/qt_config.prf \
		../qtsdk/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk/qt/mkspecs/features/default_pre.prf \
		../qtsdk/qt/mkspecs/features/release.prf \
		../qtsdk/qt/mkspecs/features/default_post.prf \
		../qtsdk/qt/mkspecs/features/warn_on.prf \
		../qtsdk/qt/mkspecs/features/qt.prf \
		../qtsdk/qt/mkspecs/features/unix/opengl.prf \
		../qtsdk/qt/mkspecs/features/unix/thread.prf \
		../qtsdk/qt/mkspecs/features/moc.prf \
		../qtsdk/qt/mkspecs/features/resources.prf \
		../qtsdk/qt/mkspecs/features/uic.prf \
		../qtsdk/qt/mkspecs/features/yacc.prf \
		../qtsdk/qt/mkspecs/features/lex.prf \
		../qtsdk/qt/mkspecs/features/include_source_dir.prf \
		ECGKW.pro
QMAKE_TARGET  = ECGKW
DESTDIR       = 
TARGET        = ECGKW

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ECGKW.pro  ../qtsdk/qt/mkspecs/linux-g++/qmake.conf ../qtsdk/qt/mkspecs/common/g++.conf \
		../qtsdk/qt/mkspecs/common/unix.conf \
		../qtsdk/qt/mkspecs/common/linux.conf \
		../qtsdk/qt/mkspecs/qconfig.pri \
		../qtsdk/qt/mkspecs/features/qt_functions.prf \
		../qtsdk/qt/mkspecs/features/qt_config.prf \
		../qtsdk/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk/qt/mkspecs/features/default_pre.prf \
		../qtsdk/qt/mkspecs/features/release.prf \
		../qtsdk/qt/mkspecs/features/default_post.prf \
		../qtsdk/qt/mkspecs/features/warn_on.prf \
		../qtsdk/qt/mkspecs/features/qt.prf \
		../qtsdk/qt/mkspecs/features/unix/opengl.prf \
		../qtsdk/qt/mkspecs/features/unix/thread.prf \
		../qtsdk/qt/mkspecs/features/moc.prf \
		../qtsdk/qt/mkspecs/features/resources.prf \
		../qtsdk/qt/mkspecs/features/uic.prf \
		../qtsdk/qt/mkspecs/features/yacc.prf \
		../qtsdk/qt/mkspecs/features/lex.prf \
		../qtsdk/qt/mkspecs/features/include_source_dir.prf \
		/home/envek/qtsdk/qt/lib/libQtOpenGL.prl \
		/home/envek/qtsdk/qt/lib/libQtGui.prl \
		/home/envek/qtsdk/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../qtsdk/qt/mkspecs/linux-g++ -unix -o Makefile ECGKW.pro
../qtsdk/qt/mkspecs/common/g++.conf:
../qtsdk/qt/mkspecs/common/unix.conf:
../qtsdk/qt/mkspecs/common/linux.conf:
../qtsdk/qt/mkspecs/qconfig.pri:
../qtsdk/qt/mkspecs/features/qt_functions.prf:
../qtsdk/qt/mkspecs/features/qt_config.prf:
../qtsdk/qt/mkspecs/features/exclusive_builds.prf:
../qtsdk/qt/mkspecs/features/default_pre.prf:
../qtsdk/qt/mkspecs/features/release.prf:
../qtsdk/qt/mkspecs/features/default_post.prf:
../qtsdk/qt/mkspecs/features/warn_on.prf:
../qtsdk/qt/mkspecs/features/qt.prf:
../qtsdk/qt/mkspecs/features/unix/opengl.prf:
../qtsdk/qt/mkspecs/features/unix/thread.prf:
../qtsdk/qt/mkspecs/features/moc.prf:
../qtsdk/qt/mkspecs/features/resources.prf:
../qtsdk/qt/mkspecs/features/uic.prf:
../qtsdk/qt/mkspecs/features/yacc.prf:
../qtsdk/qt/mkspecs/features/lex.prf:
../qtsdk/qt/mkspecs/features/include_source_dir.prf:
/home/envek/qtsdk/qt/lib/libQtOpenGL.prl:
/home/envek/qtsdk/qt/lib/libQtGui.prl:
/home/envek/qtsdk/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qtsdk/qt/mkspecs/linux-g++ -unix -o Makefile ECGKW.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ECGKW1.0.0 || $(MKDIR) .tmp/ECGKW1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ECGKW1.0.0/ && $(COPY_FILE) --parents mainwindow.h glwidget.h precompile.h .tmp/ECGKW1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/ECGKW1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp glwidget.cpp .tmp/ECGKW1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/ECGKW1.0.0/ && (cd `dirname .tmp/ECGKW1.0.0` && $(TAR) ECGKW1.0.0.tar ECGKW1.0.0 && $(COMPRESS) ECGKW1.0.0.tar) && $(MOVE) `dirname .tmp/ECGKW1.0.0`/ECGKW1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ECGKW1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_glwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_glwidget.cpp
moc_mainwindow.cpp: mainwindow.h
	/home/envek/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_glwidget.cpp: glwidget.h
	/home/envek/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) glwidget.h -o moc_glwidget.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		icons/arrow-270.png \
		icons/arrow-resize-090.png \
		icons/arrow-180.png \
		icons/control.png \
		icons/ruler-triangle.png \
		icons/application-resize-actual.png \
		icons/arrow-090.png \
		icons/door-open-out.png \
		icons/information-white.png \
		icons/property-blue.png \
		icons/application-resize-full.png \
		icons/arrow.png \
		icons/magnifier-zoom.png \
		icons/question-white.png \
		icons/control-stop-square.png
	/home/envek/qtsdk/qt/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		glwidget.h
	/home/envek/qtsdk/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp precompile.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

glwidget.o: glwidget.cpp glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o glwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

